name: empresta
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  #management dependencies
  get: ^4.6.6
  intl: ^0.19.0
  
  #lottie animations dependencies
  lottie: ^2.7.0

  #requests dependencies
  http: ^1.1.2

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  #launch icon dependecies
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/app/assets/empresta_icon.png"
  min_sdk_android: 21


flutter:

  uses-material-design: true

  assets:
    - lib/app/assets/nice.json
    - lib/app/assets/empty_result.json
    - lib/app/assets/banco_bmg.png
    - lib/app/assets/banco_pan.png
    - lib/app/assets/banco_ole.png


